@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "Wallet Unit" #lightgreen
participant "OS/Browser"
participant "RP App"
participant "RP BE"
participant Issuer

activate User
User -> "RP App": Pay for order with EUDIW
activate "RP App"
    "RP App" -> "OS/Browser": User Agent Allows Protocol Request
    activate "OS/Browser"
        return User Agent Allows Protocol Response
    note right
    In case User Agent does not support DC API
    i.e. Firefox or Linux OS solution should
    fallback on QR code or deeplink navigation.
    See diagram for deeplink in integration

    end note
    "RP App" -> "RP BE": Prepare Openid4VP Request with Payment
    activate "RP BE"
        return Signed Openid4VP Request
    "RP App" -> "OS/Browser": DC API Openid4VP request
== Payment Authorization ==
deactivate "RP App"
activate "OS/Browser"
note left
    here is simplification,
    user may choose "Wallet Unit" with credential,
    which they will use,
    in case of A.1 it should be generic SUA  attestation
    in case of A.2 it should be IBAN as SUA attestation
    in case of B.1 it should be generic SUA  attestation
    in case of B.2 it should be Card attestation as SUA attestation

end note
"OS/Browser" -> "Wallet Unit": Invoke with Openid4VP request
deactivate "OS/Browser"
note left
We have gap that merchant will have to
send transaction_data
in DC API Credential Request in open form
and therefore it is available of platform to inspect.
This is most likely privacy issue that needs to be addressed in protocols.
end note
activate "Wallet Unit"
"Wallet Unit" -> "Wallet Unit": Validate DC API Credential request
opt vct metadata cache empty
loop vct in payment credentials
"Wallet Unit" -> Issuer: Get SD-JWT vct metadata
    activate Issuer
    return vct metadata
end
"Wallet Unit" -> "Wallet Unit": Evalute credential eligibility for payment type
end
"Wallet Unit" -> "Wallet Unit": Display Payment
User -> "Wallet Unit": Confirm Payment & authenticate for SUA key
"Wallet Unit" -> "Wallet Unit": Attach transaction data  KB-JWT to SUA presentation, create final VP token
"Wallet Unit" -> "Wallet Unit": Encrypt with Merchant public key
return encrypted response
activate "OS/Browser"
"OS/Browser" --> "RP App":  DC API credential response
deactivate "OS/Browser"
activate "RP App"

"RP App" -> "RP BE": POST /response with encrypted vptoken
note left
Not standardised, depends on merchant integration patterns
end note
    activate "RP BE"
     "RP BE"-> "RP BE": decrypt and validate vptoken
    return response OK/NOK



@enduml