@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "Wallet Unit" #lightgreen
participant "OS/Browser"
participant "RP App"
participant "RP BE"

activate User
User -> "RP App": Pay for order with EUDIW
activate "RP App"

== Payment Authorization ==

    "RP App" -> "RP BE": Prepare Request URI with payment data
    activate "RP BE"
        return Request URI
    "RP App" -> "RP App": Display QR code with deeplink
deactivate "RP App"
alt scan QR code (cross device)
    "User" -> "Wallet Unit": Open camera
    "Wallet Unit" -->  "RP App": Scan QR code with camera
    "Wallet Unit" -> "Wallet Unit": Process scaned request
else click on deeplink
    User -> "RP App": Click on deeplink QR code
    activate "RP App"
        "RP App" -> "OS/Browser": Open deeplink
    deactivate "RP App"
    activate "OS/Browser"
    opt More Wallets in OS
    "User"-> "OS/Browser": Choose "Wallet Unit"
    "OS/Browser" -> "Wallet Unit": Invoke with Openid4VP request
    deactivate "OS/Browser"
end

activate "Wallet Unit"

"Wallet Unit" -> "RP BE": POST /par (with Wallet Metadata)
note left
We instigate that merchant will use
only reference to Request Object
and Request data will be downloaded
from "RP BE" server see
5.10. Request URI Method POST  in OpenID4VP
end note
activate "RP BE"
    return OpenID4VP encrypted request
"Wallet Unit" -> "Wallet Unit": Decrypt and validate credential request
opt vct metadata cache empty
loop vct in payment credentials
"Wallet Unit" -> Issuer: Get SD-JWT vct metadata
    activate Issuer
    return vct metadata
end
"Wallet Unit" -> "Wallet Unit": Evalute credential eligibility for payment type
end
"Wallet Unit" -> "Wallet Unit": Display Payment
User -> "Wallet Unit": Confirm Payment & authenticate for SUA key
"Wallet Unit" -> "Wallet Unit": Attach transaction data  KB-JWT to SUA presentation, create final VP token
"Wallet Unit" -> "Wallet Unit": Encrypt with Merchant public key
"Wallet Unit" -> "RP BE": /POST response_uri from request
note left
Direct_post.jwt with signed and encrypted response must be used,
also validation on response domain given request by Merchant
end note
activate "RP BE"
    return deeplink redirect to "RP App"
"Wallet Unit" -> "OS/Browser": Deeplink redirect to "RP App"
activate "OS/Browser"
"OS/Browser" --> "RP App":  Invoke "RP App" with redirect
deactivate "OS/Browser"
activate "RP App"
    "RP App" -> "RP App": Continue with merchant flow


@enduml