@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "Wallet Unit" #lightgreen
participant "OS/Browser"
participant "RP App"
participant "RP BE"




activate User
User -> "RP App": Pay for order with EUDIW
activate "RP App"


    "RP App" -> "OS/Browser": User Agent Allows Protocol Request
    activate "OS/Browser"
        return User Agent Allows Protocol Response
    note right
    In case User Agent does not support DC API
    i.e. Firefox or Linux OS solution should
    fallback on QR code or deeplink navigation.
    end note
== Payment Authorization ==
alt  DC API available
|||
    ref over User, "RP BE"
        DC API flow
    end ref
    |||
else DC API not available
|||
    ref over User, "RP BE"
        Deeplink flow
    end ref
    |||
end
@enduml