@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant User
participant Wallet
participant Browser
participant Issuer
participant Bank

== Credential Offer ==
activate User
User -> Bank: Request Credential from Bank
activate Bank
    Bank -> Bank: Display credential offer
User -> Wallet **: Open Wallet
activate Wallet
    Wallet -> Wallet: Scan Credential offer
Wallet -> Issuer: .well-known/openid-credential-issuer
    activate Issuer
    return Credential Issuer metadata
Wallet -> Issuer: .well-known/openid-configuration
   note left
   For simplicity OAuth Authorization Server is part of issuer,
    but in RL may be different.
    OAuth request are prefixed by /oauth prefix in URL
   URL might also be for oauth authorization metadata URL,
   not necessary OpenID.
   end note
   activate Issuer
   return openid server metadata
   Wallet -> Issuer: /oauth/par
   activate Issuer
        return auth request id
   Wallet -> Issuer: /oauth/auth
   activate Issuer
        return HTTP 302 to auth page
   Wallet -> Browser **: auth page
   activate Browser
   Browser -> Issuer: /login
   activate Issuer
            Issuer -> Issuer: prepare OpenID4VP request for WUA + PID/SUA
        return page with deep link
   Browser --> Wallet: invoke with presentation request
   activate Wallet
   Wallet -> Wallet: process presentation as Deep link flow
   Wallet --> Browser: redirect back
   deactivate Wallet
   Browser -> Issuer: initate redirect back to Wallet
   activate Issuer
        Issuer -> Bank: Send user authorization
        activate Bank
        return OK/NOK
   return redirect to Wallet
   return Wallet callback with code
   Wallet -> Issuer: /oauth/token (optionally with DPoP)
   activate Issuer
    return Access_token + refresh_token
   Wallet -> Issuer: /nonce
   activate Issuer
    return fresh nonce
   Wallet -> Issuer: /credential
   activate Issuer
    Issuer -> Bank: get credentials data
    activate Bank
    return credentials data
   return credentials
   Wallet -> Wallet: Display issued credentials
   User -> Wallet: accept credentials
   Wallet -> Issuer: /notification (with credential accepted)
   activate Issuer
   return  HTTP 204






@enduml