@startuml

'https://plantuml.com/sequence-diagram

autonumber
participant User
participant Wallet
participant Browser
participant Issuer
participant Bank

loop Periodic attestation validity check
activate Wallet
    Wallet -> Wallet: Check attestation validity
    opt attestation is invalid and can be refreshed
        Wallet -> Issuer: /token with DPoP, and refresh_token grant
        activate Issuer
        return AT and new RT
        Wallet -> Issuer: /credential with new AT
        activate Issuer
            Issuer -> Bank: Get credential data
            activate Bank
            return credentail data
            return issued new credentais
        Wallet -> Issuer: notify credentials accepted
        activate Issuer
        return HTTP 204
    end
    opt attestation cannot be refreshed
        Wallet -> User: Notify credential expired
        ref over User, Bank
         New Credential issuance
         end ref
    end
end
@enduml