@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "Wallet Unit" #lightgreen
participant OS
participant "Merchant App"
participant DeviceBrowser
participant PISP
participant ASPSP
participant Issuer

activate User
User -> "Merchant App": Pay for order with EUDIW
note right
Assumption is to be on mobile phone
end note
activate "Merchant App"
    "Merchant App" -> PISP: Intiate payment
    activate PISP
    PISP -> ASPSP: POST /transaction
    note right
    Regular PSD2 Account-to-account transaction
    end note
    activate ASPSP
        return authorization link
    return authorization link
    "Merchant App" -> DeviceBrowser **: Open authorization link
    activate DeviceBrowser
    DeviceBrowser -> ASPSP: get transaction to authorize
    activate ASPSP
    return transaction to authorize
    DeviceBrowser -> DeviceBrowser: Display transaction to authorize
    User -> DeviceBrowser: Choose EUDIW to authorize
    DeviceBrowser -> OS: User Agent Allows Protocol Request

    activate OS
        return User Agent Allows Protocol Response
    note right
    In case User Agent does not support DC API
    i.e. Firefox or Linux OS solution should
    fallback on QR code or deeplink navigation.
    See diagram for deeplink in integration
    end note
    DeviceBrowser-> ASPSP: Prepare Openid4VP Request with Payment
    activate ASPSP
        return Signed Openid4VP Request
    DeviceBrowser -> OS: DC API Openid4VP request
== Payment Authorization ==
activate OS
note left
    here is simplification,
    user may choose "Wallet Unit" with credential,
    which they will use,
    in case of A.1 it will be SUA  attestation
end note

OS -> OS: Evalute credential eligibility for payment type
OS -> OS: Display Payment
User -> OS: Confirm presentation

OS -> "Wallet Unit": Invoke with Openid4VP request
deactivate OS

activate "Wallet Unit"
"Wallet Unit" -> "Wallet Unit": Validate DC API Credential request
"Wallet Unit" -> "Wallet Unit": Attach transaction data  KB-JWT to SUA presentation, create final VP token
"Wallet Unit" -> "Wallet Unit": Encrypt with Merchant public key
return encrypted response
activate OS

OS --> DeviceBrowser:  DC API credential response
deactivate OS


DeviceBrowser -> ASPSP: POST /response with encrypted vptoken
note left
Not standardised, depends on merchant integration patterns
end note
    activate ASPSP
     ASPSP-> ASPSP: decrypt and validate vptoken
     return result
    DeviceBrowser -> DeviceBrowser !!: Close browser
loop check transaction status
 "Merchant App" -> PISP: Get transaction status
 activate PISP
 PISP -> ASPSP: get transaction status
 activate ASPSP
  return transaction status (NOT FINISHED, OK, NOT )
 return transaction status (NOT FINISHED, OK, NOT )
 opt transaction OK/NOK
    "Merchant App" -> "Merchant App": Display payment confirmation/refusal
  end
end



@enduml