@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "Wallet Unit" #lightgreen
participant OS
participant DeviceBrowser
participant "Merchant App"
participant PISP
participant ASPSP

activate User
User -> "Merchant App": Pay for order with EUDIW
note right
Assumption is to be on mobile phone
end note
activate "Merchant App"
    "Merchant App" -> PISP: Intiate payment
    activate PISP
    PISP -> ASPSP: POST /transaction
    note right
    Regular PSD2 Account-to-account transaction
    end note
    activate ASPSP
        return authorization link
    return authorization link
    activate DeviceBrowser
    DeviceBrowser -> ASPSP: get transaction to authorize
    activate ASPSP
    return transaction to authorize
    DeviceBrowser -> DeviceBrowser: Display transaction to authorize
    User -> DeviceBrowser: Choose EUDIW to authorize
    opt check for DC API support
    DeviceBrowser -> OS: User Agent Allows Protocol Request

    activate OS
        return User Agent Allows Protocol Response
    note right
    This is case that ASPSP or User Agent does not support DC API
    end note
    end

== Payment Authorization ==

    DeviceBrowser -> ASPSP: Prepare Request URI with payment data
    activate ASPSP
        return Request URI
    DeviceBrowser -> DeviceBrowser: Display QR code with deeplink

alt scan QR code (cross device)
    "User" -> "Wallet Unit": Open camera
    "Wallet Unit" -->  DeviceBrowser: Scan QR code with camera
    "Wallet Unit" -> "Wallet Unit": Process scaned request
else click on deeplink
    User -> DeviceBrowser: Click on deeplink QR code
    activate DeviceBrowser
        DeviceBrowser -> OS: Open deeplink
    deactivate DeviceBrowser
    activate OS
    opt More Wallets in OS
    "User"-> OS: Choose "Wallet Unit"
    OS -> "Wallet Unit": Invoke with Openid4VP request
    deactivate OS
end

activate "Wallet Unit"

"Wallet Unit" -> ASPSP: POST /par (with Wallet Metadata)
note left
We instigate that merchant will use
only reference to Request Object
and Request data will be downloaded
from ASPSP server see
5.10. Request URI Method POST  in OpenID4VP
end note
activate ASPSP
    return OpenID4VP encrypted request
"Wallet Unit" -> "Wallet Unit": Decrypt and validate credential request
opt vct metadata cache empty
loop vct in payment credentials
"Wallet Unit" -> Issuer: Get SD-JWT vct metadata
    activate Issuer
    return vct metadata
end
"Wallet Unit" -> "Wallet Unit": Evalute credential eligibility for payment type
end
"Wallet Unit" -> "Wallet Unit": Display Payment
User -> "Wallet Unit": Confirm Payment & authenticate for SUA key
"Wallet Unit" -> "Wallet Unit": Attach transaction data  KB-JWT to SUA presentation, create final VP token
"Wallet Unit" -> "Wallet Unit": Encrypt with Merchant public key
"Wallet Unit" -> ASPSP: /POST response_uri from request
note left
Direct_post.jwt with signed and encrypted response must be used,
also validation on response domain given request by Merchant
end note
activate ASPSP
    return deeplink redirect to "Merchant App"
"Wallet Unit" -> OS: redirect back to DeviceBrowser
activate OS
OS --> DeviceBrowser:  redirect back
deactivate OS

    DeviceBrowser -> DeviceBrowser !! : redirect to app or closer browser

loop check transaction status
 "Merchant App" -> PISP: Get transaction status
 activate PISP
 PISP -> ASPSP: get transaction status
 activate ASPSP
  return transaction status (NOT FINISHED, OK, NOT )
 return transaction status (NOT FINISHED, OK, NOT )
 opt transaction OK/NOK
    "Merchant App" -> "Merchant App": Display payment confirmation/refusal
  end
end

@enduml