@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User 
participant "Wallet Unit" #lightgreen
participant "OS/Browser"
participant MerchantApp
participant PISP
participant ASPSP
participant Bank



activate User
User -> MerchantApp: Pay for order with EUDIW
activate MerchantApp
    MerchantApp -> "OS/Browser": User Agent Allows Protocol Request
    activate "OS/Browser"
        return User Agent Allows Protocol Response
    note right
    In case User Agent does not support DC API
    i.e. Firefox or Linux OS solution should
    fallback on QR code or deeplink navigation.
    See diagram for deeplink in integration

    end note
    MerchantApp -> PISP: Prepare payment
        activate PISP
        note left
        Berlin Group assumes that transaction
        is first created at ASPSP berfore authorization
        This is changed for Wallet flow.
        end note
        return


    MerchantApp -> PISP: Prepare Request
    activate PISP
        return Request
    MerchantApp -> "OS/Browser": DC API Openid4VP request
== Payment Authorization ==
activate "OS/Browser"
note left   
    here is simplification,
    user may choose "Wallet Unit" with credential,
    which they will use, in case of A.2 it should be IBAN as SUA attestation
end note
"OS/Browser" -> "OS/Browser": Evaluate credential eligibility for payment type

"OS/Browser" -> "OS/Browser": Display Payment
User -> "OS/Browser": Confirm Payment & authenticate for SUA key
"OS/Browser" -> "Wallet Unit": Invoke with Openid4VP request
deactivate "OS/Browser"

activate "Wallet Unit"
"Wallet Unit" -> "Wallet Unit": Validate credential request


"Wallet Unit" -> "Wallet Unit": Attach transaction data  KB-JWT to SUA presentation, create final VP token
"Wallet Unit" -> "Wallet Unit": Encrypt with PISP public key
return encrypted response
activate "OS/Browser"
"OS/Browser" --> MerchantApp:  DC API response
deactivate "OS/Browser"

MerchantApp -> PISP: POST /response with encrypted vptoken
note left
Not standardised, depends on merchant integration patterns
end note
== Payment initiation ==
    activate PISP
     PISP-> PISP: decrypt and validate vptoken

        PISP -> ASPSP: PSD2 Open Banking Signed Payment Request
        activate ASPSP
        return OK/NOK
    return trx id

loop poll trx status
    MerchantApp -> PISP: Get payment status
    activate PISP
        PISP -> ASPSP: Get payment status
        activate ASPSP
        return processing/executed/declined
     return processing/executed/declined
end loop

@enduml