@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "Wallet Unit" #lightgreen
participant "OS/Browser"
participant MerchantApp
participant PISP
participant ASPSP
participant Bank



activate User
User -> MerchantApp: Pay for order with EUDIW
activate MerchantApp
    MerchantApp -> "OS/Browser": User Agent Allows Protocol Request
    activate "OS/Browser"
        return User Agent Allows Protocol Response
    MerchantApp -> PISP: Prepare payment
        activate PISP
        note left
        Berlin Group assumes that transaction
        is first created at ASPSP berfore authorization
        This might be changed for Wallet flow.
        end note
        return

== Payment Authorization ==

    note right
     In case User Agent does not support DC API
    i.e. Firefox or Linux OS solution should
    fallback on QR code or deeplink navigation.
    See diagram for DC API

    end note
    MerchantApp -> PISP: Prepare Request URI
    activate PISP
        return Request URI
    MerchantApp -> MerchantApp: Display QR code with deeplink
deactivate MerchantApp
alt scan QR code (cross device)
    "User" -> "Wallet Unit": Open camera
    "Wallet Unit" -->  MerchantApp: Scan QR code with camera
    "Wallet Unit" -> "Wallet Unit": Process scaned request
else click on deeplink
    User -> MerchantApp: Click on deeplink QR code
    activate MerchantApp
        MerchantApp -> "OS/Browser": Open deeplink
    deactivate MerchantApp
    activate "OS/Browser"
    opt More Wallets in OS
    "User"-> "OS/Browser": Choose "Wallet Unit"
    "OS/Browser" -> "Wallet Unit": Invoke with Openid4VP request
    deactivate "OS/Browser"
end

activate "Wallet Unit"

"Wallet Unit" -> PISP: POST /par (with Wallet Metadata)
note left
We instigate that merchant will use
only reference to Request Object
and Request data will be downloaded
from PISP server see
5.10. Request URI Method POST  in OpenID4VP
end note
activate PISP
    return OpenID4VP encrypted request
"Wallet Unit" -> "Wallet Unit": Decrypt and validate credential request
opt vct metadata cache empty
loop vct in payment credentials
"Wallet Unit" -> Bank: Get SD-JWT vct metadata
    activate Bank
    return vct metadata
end
"Wallet Unit" -> "Wallet Unit": Evalute credential eligibility for payment type

end
"Wallet Unit" -> "Wallet Unit": Display Payment
User -> "Wallet Unit": Confirm Payment & authenticate for SUA key
"Wallet Unit" -> "Wallet Unit": Attach transaction data  KB-JWT to SUA presentation, create final VP token
"Wallet Unit" -> "Wallet Unit": Encrypt with PISP public key
"Wallet Unit" -> PISP: /POST response_uri from request
note left
Direct_post.jwt with signed and encrypted response must be used,
also validation on response domain given request by Merchant
end note
activate PISP
    return deeplink redirect to MerchantApp
"Wallet Unit" -> "OS/Browser": Deeplink redirect to MerchantApp
activate "OS/Browser"
"OS/Browser" --> MerchantApp:  Invoke MerchantApp with redirect
deactivate "OS/Browser"
activate MerchantApp
    MerchantApp -> MerchantApp: Continue with merchant flow

== Payment initiation ==
    activate PISP
     PISP-> PISP: decrypt and validate vptoken

        PISP -> ASPSP: PSD2 Open Banking Signed Payment Request
        activate ASPSP
        return OK/NOK
    return trx id

loop poll trx status
    MerchantApp -> PISP: Get payment status
    activate PISP
        PISP -> ASPSP: Get payment status
        activate ASPSP
        return processing/executed/declined
     return processing/executed/declined
end loop

@enduml